http: 
  - server:
      listen: 8999
      server_name: localhost
      error_log: ./logs/error_logs.txt
      access_log: ./logs/access_logs.txt

      locations: 
         - location:
             url: /api
             root: ./wwwroot
             index: poets.html
         - location:
             url: ~ /proxy.*
             proxy_pass: http://127.0.0.1:8997/api
             proxy_set_header: Host localhost
         - location:
             url: /poets
             index: poets.html
         - location:
             url: /test
             root: ./wwwroot/test
             index: index.php
  - server:
      listen: 8997
      server_name: bingyan/0.1.0

#   - server:
#       listen: 8999
#       server_name: bingyan/0.1.0
