http: 
  - server:
      listen: 80
      server_name: localhost
      error_log: /home/zlf/c++/logs/error_logs.txt
      access_log: /home/zlf/c++/logs/access_logs.txt

      locations: 
         - location:
             url: /api
             root: /home/zlf/c++/proxy_server/wwwroot
             index: index.html